/**https://leetcode.com/problems/find-the-difference/ */
//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.
// 
//Example 1:
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
//Example 2:
//Input: s = "", t = "y"
//Output: "y"
// 
//Constraints:
//	0 <= s.length <= 1000
//	t.length == s.length + 1
//	s and t consist of lowercase English letters.
char findTheDifference(char* s, char* t) {
    int i;
    int a[26] = {0};
    for(i = 0; s[i] != '\0'; i++)
        a[s[i] - 'a']++;
    for(i = 0; t[i] != '\0'; i++)
        a[t[i] - 'a']--;
    for(i = 0; i < 26; i++)
        if(a[i] == -1)
            return i + 'a';
    return 0;    
}