#https://leetcode.com/problems/find-the-difference/
#You are given two strings s and t.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Return the letter that was added to t.
# 
#Example 1:
#Input: s = "abcd", t = "abcde"
#Output: "e"
#Explanation: 'e' is the letter that was added.
#Example 2:
#Input: s = "", t = "y"
#Output: "y"
# 
#Constraints:
#	0 <= s.length <= 1000
#	t.length == s.length + 1
#	s and t consist of lowercase English letters.
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        # Convert strings to lists for easier manipulation
        s_list = list(s)
        t_list = list(t)
        
        # Iterate over the characters in t
        for char in t_list:
            # If the character is already in s, remove it
            if char in s_list:
                s_list.remove(char)
            # If the character is not in s, it must have been added to t
            else:
                return char
            
        