/**https://leetcode.com/problems/find-the-difference/ */
//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.
// 
//Example 1:
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
//Example 2:
//Input: s = "", t = "y"
//Output: "y"
// 
//Constraints:
//	0 <= s.length <= 1000
//	t.length == s.length + 1
//	s and t consist of lowercase English letters.
class Solution {
public:
    char findTheDifference(string s, string t) {
        int freq[26] = {0};
        for (char c : s) freq[c - 'a']++;
        for (char c : t) freq[c - 'a']--;
        for (int i = 0; i < 26; i++) if (freq[i]!= 0) return 'a' + i;
        return 0; // This line is unreachable, but added for completeness. 0 is returned when s and t are empty.
        
    }
};